name: Discord Webhook Notify
author: rjstone
description: >
  Send notifications to Discord using a webhook.
  Works with all execution environments including windows, macos, and linux.
inputs:
  webhookUrl:
    description: Discord webhook URL. Should be stored in a secret and inserted as a context expression.
    required: true
  severity:
    description: Severity level - info, warn, or error
    required: false
    default: error
  description:
    description: Embed notification message. Use context expressions and environment variables to provide information. Default provides branch and user info.
    required: false
  details:
    description: Additional text after the notification message in case you want to retain the default message.
    required: false
  footer:
    description: Footer for the embed. Defaults to severity.
    required: false
  text:
    description: Text to be sent as normal text above the embed. Use context expressions and environment variables to provide information.
    required: false
  username:
    description: Username to display in discord.
    required: false
  color:
    description: Notification color in the form poundsign rrggbb (hex). Default determined by severity.
    required: false
  avatarUrl:
    description: URL to png of discord avatar to use. Default is the GitHub monochrome mark cat logo.
    required: false
runs:
  using: "node20"
  main: "index.js"
branding:
  color: orange
  icon: alert-triangle
